apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nonseed-deployment
  name: nonseed-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nonseed
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nonseed
    spec:
      containers:
        - image: archit05/gossipprotocol:0.0.3
          name: gossipprotocol
          ports:
            - containerPort: 8080
          resources: {}
          env:
            - name: MY_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: IS_SEED
              value: 'N'
            - name: SEED_ADDRESS
              value: '10.1.1.70:8080'
status: {}