apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: seed
  name: seed
spec:
  containers:
    - image: archit05/gossipprotocol:0.0.3
      name: seed
      ports:
        - containerPort: 8080
      resources: {}
      env:
        - name: MY_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: IS_SEED
          value: 'Y'
        - name: SEED_ADDRESS
          value: '10.1.1.0:8080'
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}