apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: seed-svc
    run: seed-svc
  name: seed-svc
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: seed
  type: NodePort
status:
  loadBalancer: {}
